name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build -t book-app .
        docker run -d -p 3000:3000 -p 3030:3030 --name book-app-cont book-app npm run test:ui
